name: Run Cypress Tests

on:
  push:
    branches:
      - main

jobs:
  run-cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo 2
        uses: actions/checkout@v2
        with:
          repository: DenzMoses/testrepo2
          ref: main
          path: testrepo2 # This is the directory where Repo 2 will be checked out

      - name: Install Dependencies
        working-directory: ./testrepo2
        run: npm install

      - name: Cypress run
        working-directory: ./testrepo2
        run: |
          npm start &
          npx cypress run
          
